name: memora-opensearch
services:
  opensearch-node1:
    image: opensearchproject/opensearch:3.2.0
    container_name: memora-opensearch
    environment:
      - cluster.name=memora-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os-data-32:/usr/share/opensearch/data
    ports:
      - "9200:9200"   # OpenSearch API
      - "9600:9600"   # Performance analyzer

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.2.0
    container_name: memora-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
    ports:
      - "5601:5601"   # Dashboards UI
    depends_on:
      - opensearch-node1

volumes:
  os-data-32:
