# config/retrieval.yaml
# Controls multi-stage retrieval and ranking for memory queries.

stages:
  episodic:
    enabled: true
    top_k: 100
    query_type: bm25         # BM25 or match
    filters:
      default_scope: ["this_task", "project"]
      recent_days: 0         # diagnostic: disable recency cutoff temporarily
  semantic:
    enabled: false
    top_k: 150
    ann_candidates: 200
    metric: cosine
    filters:
      default_scope: ["this_task", "project"]
      api_version: ">=3.0"   # default version filter if present
  facts:
    enabled: false
    hops: 2                  # expand neighbors up to 2 hops
    top_k: 40

fusion:
  method: rrf
  rrf_k: 60
  normalize_scores: true

rerank:
  enabled: false
  max_candidates: 32         # cap for reranker (smoke p95 ~801ms at k=32)
  model: cross-encoder-mini  # placeholder; can be ML Commons model id or external service
  budget_ms: 1200            # max latency budget in ms
  budget_usd: 0.01           # optional cost budget per retrieval

diversity:
  enabled: false
  method: mmr
  lambda: 0.8                # tradeoff relevance vs. diversity
  min_distance: 0.2          # threshold for considering items duplicates
  max_per_tag: 5             # prevent one tag (e.g., "error") from dominating

lexical:
  # Lexical/BM25 query tuning
  multi_match_type: cross_fields  # or best_fields for independent field scoring
  tie_breaker: 0.3
  min_should_match_pct: 0    # diagnostic: disable MSM to prevent over-pruning
  use_shingles: true         # use *.shingles fields when available

time_decay:
  enabled: false
  episodic:
    field: ts
    half_life_days: 45
    weight: 0.25
  semantic:
    field: last_used
    half_life_days: 45
    weight: 0.15

filters:
  # Global filters applied to every retrieval
  exclude_tags: ["secret", "sensitive"]
  scope_order: ["this_task", "project", "global"]

fallbacks:
  # If no results found in semantic, back off to episodic only
  semantic_empty_to_episodic: true
  # If still nothing, fall back to project-wide default docs
  project_fallback_docs: true

diagnostics:
  enabled: false
  guard_traces: false
  fallback_traces: false
  request_response_traces: false
