name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Coverage (text summary)
        run: npm run coverage

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit
    services:
      opensearch:
        image: opensearchproject/opensearch:2.18.0
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -fsSL http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30
        env:
          discovery.type: single-node
          plugins.security.disabled: "true"
          bootstrap.memory_lock: "true"
          OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Wait for OpenSearch
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:9200 >/dev/null; then
              echo "OpenSearch is up"
              break
            fi
            echo "Waiting for OpenSearch..."
            sleep 2
          done

      - name: Run Integration Tests
        env:
          INTEGRATION: "1"
          OPENSEARCH_URL: "http://localhost:9200"
        run: npm run test:integration
